services:
  mysqldb:  # Cambié el nombre de 'database' a 'mysqldb'
    image: mysql:8.0
    ulimits:
      nofile: 
        soft: 1048576
        hard: 1048576
    ports:
      - 3307:3306
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-backend-Santiii4.git
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - app_network
    environment:
      - MYSQLDB_HOST=mysqldb  # Asegúrate de que esto coincide
      - MYSQLDB_USER=root
      - MYSQLDB_ROOT_PASSWORD=root
      - MYSQLDB_DATABASE=ecommerce
      - MYSQLDB_PORT=3306
      - PORT=5000

  frontend:
    build:
      context: https://github.com/etec-integration-project/etec-pi-2024-frontend-Santiii4.git
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network
    environment:
      - PORT=3000

networks:
  app_network:

volumes:
  db_data:



